version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install

  build:
    commands:
      - echo Building Tesselo Frontend Vue Application for stage $STAGE
      - npm run build:$STAGE
      - echo "Pushing new build to s3://$BUCKET"
      - aws s3 sync --exclude *.js.map --acl public-read dist/ s3://$BUCKET
      - npm run e2e test/pupeteer/login.test.js
