version: 0.2

phases:
  pre_build:
    commands:
      - echo "Upgrading npm to latest version 5.x"
      - npm install -g npm@latest-5
      - echo "Installing npm dependencies"
      - npm install
  build:
    commands:
      - echo Building Tesselo Frontend Vue Application for stage $STAGE
      - npm run build:$STAGE
      - echo "Pushing new build to s3://$BUCKET"
      - aws s3 sync --acl public-read dist/ s3://$BUCKET
