version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - echo Building Tesselo Frontend Vue Application for stage
      - npm run build:production
      - echo "Pushing new build to s3://$BUCKET"
      - aws s3 sync --exclude *.js.map --acl public-read dist/ s3://$BUCKET
