name: Tesselo app CI

on:
  push:
    branches:
      - test-actions
  pull_request:
    branches:
      - test-actions

jobs:
  js_dependencies:
    name: Javascript dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout tesselo-app
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x

      - name: Attempt to use cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
  
  build:
    name: Build tesselo-app
    needs: [js_dependencies]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tesselo-appo
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      
      - name: Use modules cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}
      
      - name: Use build cache
        uses: actions/cache@v2
        id: build-cache
        with:
          path: ./dist
          key: ${{ runner.os }}-npm-${{ github.sha }}

      - name: Build App
        run: npm run build:production
  
  deploy_to_staging:
      name: Deploy to staging
      needs: [js_dependencies, build]
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout tesselo-app
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      
      - name: Use modules cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}

      - name: Use build cache
        uses: actions/cache@v2
        id: build-cache
        with:
          path: ./dist
          key: ${{ runner.os }}-npm-${{ github.sha }}

      - name: Push new build to S3
        run:
          aws s3 sync --exclude *.js.map --acl public-read dist/ s3://${{ env.BUCKET }}
        env:
          BUCKET: staggingapp.tesselo.com

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloud-front-action@v1.3
        env: 
          DISTRIBUTION: E1X9H8PC4Q5SNJ
          PATHS: '/*' 

  tests_execution:
      name: App tests
      needs: [js_dependencies, build, deploy_to_staging]
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout tesselo-app
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      
      - name: Use modules cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}

      - name: Use build cache
        uses: actions/cache@v2
        id: build-cache
        with:
          path: ./dist
          key: ${{ runner.os }}-npm-${{ github.sha }}

      - name: Login test
        run: npm run tests  